### ISSUE TITLE
hashcat package - adding dependencies

### ISSUE THREAD

**Issue by D3vil0p3r** [freswa/aur#7]
Hey @freswa sorry if I open an issue here but I cannot find a repository containing Arch Linux (not AUR) packages you maintain containing [Hashcat](https://archlinux.org/packages/extra/x86_64/hashcat/) package.

First of all, I appreciate you maintain AUR PKGBUILD in GitHub so everyone can contribute on these packages.

About Hashcat, for users that would like to use only CPU instead of GPU for cracking hashes (mostly for users using Virtual Machines that don't provide GPU Passthrough), an additional dependency should be added:
```
pocl
```
Could you please add it to the dependencies of Hashcat package please?

**Comment by freswa** [comment]
Hi,
thank you for taking the time to report an issue. Hashcat can be used with many OpenCL implementations. Arch Linux does not provide any meta package to depend on a OpenCL implementation that can be chosen by the user. Thus depending on pocl doesn't make any sense here. We'll reconsider when there is a meta package for OpenCL available.
